# Multi-stage image for deepseek-balance
# Generated by genproj (docker-container capability, language-aware). Adjust
# for your application.
#
# Stage 1 (build): copies the full source tree, installs dependencies and
# builds the application. Stage 2 (runtime): copies only the build output /
# virtualenv and production dependencies, keeping the final image small.

FROM python:3.12-slim AS build
WORKDIR /app
COPY README.md pyproject.toml* requirements.txt* ./
RUN python -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && mkdir -p src/deepseek_balance && touch src/deepseek_balance/__init__.py \
    && if [ -f requirements.txt ]; then \
         grep -vE '^\s*(-e|--editable)\s+\.' requirements.txt > /tmp/reqs.txt || true; \
         [ -s /tmp/reqs.txt ] && /opt/venv/bin/pip install --no-cache-dir -r /tmp/reqs.txt; \
       fi \
    && if [ -f pyproject.toml ]; then \
         /opt/venv/bin/pip install --no-cache-dir .; \
       fi
COPY . .
RUN if [ -f requirements.txt ]; then \
      /opt/venv/bin/pip install --no-cache-dir -r requirements.txt; \
    elif [ -f pyproject.toml ]; then \
      /opt/venv/bin/pip install --no-cache-dir --no-deps .; \
    fi

FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*
ENV PATH="/opt/venv/bin:$PATH"
COPY --from=build /opt/venv /opt/venv
COPY . .
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s CMD curl -fsS http://127.0.0.1:3000/health || exit 1
CMD ["python", "-m", "deepseek_balance"]
